// Package catalog generates the provider catalog and capability matrix
// from every provider's metadata.yaml and manifest.yaml: see
// docs/add-a-provider.md and .github/workflows/docs.yml. This keeps the
// generated docs inside the one piece of application code this
// repository permits, rather than a separate script living outside
// tools/ (spec/00-overview.md's governing rule).
package catalog

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/esiipayment/esiipayment-spec/tools/validator/internal/model"
)

// Generate renders the provider catalog and capability matrix as
// Markdown, reading every providers/<name>/{manifest,metadata}.yaml
// except providers/_template.
func Generate(repoRoot string) (string, error) {
	providersDir := filepath.Join(repoRoot, "providers")
	entries, err := os.ReadDir(providersDir)
	if err != nil {
		return "", fmt.Errorf("reading %s: %w", providersDir, err)
	}

	type row struct {
		manifest *model.Manifest
		metadata *model.Metadata
	}
	var rows []row
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), "_") {
			continue
		}
		dir := filepath.Join(providersDir, e.Name())
		m, err := model.LoadManifest(dir)
		if err != nil {
			return "", fmt.Errorf("loading %s: %w", dir, err)
		}
		md, err := model.LoadMetadata(dir)
		if err != nil {
			return "", fmt.Errorf("loading %s: %w", dir, err)
		}
		rows = append(rows, row{manifest: m, metadata: md})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].manifest.Provider < rows[j].manifest.Provider })

	var b strings.Builder
	b.WriteString("<!-- GENERATED by `esiipayment catalog` (tools/validator): do not hand-edit. -->\n")
	b.WriteString("<!-- Regenerate with .github/workflows/docs.yml, or `esiipayment catalog` locally. -->\n\n")
	b.WriteString("# Provider Catalog\n\n")
	b.WriteString("| Provider | Country | Tier | Verification | Currencies | Operations |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, r := range rows {
		verification := r.metadata.Verification.Status
		if verification == "provisional" {
			verification = "⚠️ provisional"
		} else if verification == "verified" {
			verification = "✅ verified"
		}
		b.WriteString(fmt.Sprintf("| %s (%s) | %s | %s | %s | %s | %s |\n",
			r.manifest.DisplayName, r.manifest.Provider, r.manifest.Country, r.metadata.Tier,
			verification, strings.Join(r.manifest.Currencies, ", "), strings.Join(r.manifest.Capabilities.Operations, ", ")))
	}

	b.WriteString("\n# Capability Matrix\n\n")
	b.WriteString("| Provider | " + strings.Join(operationOrder, " | ") + " | NextAction variants |\n")
	b.WriteString("|---|" + strings.Repeat("---|", len(operationOrder)) + "---|\n")
	for _, r := range rows {
		supported := map[string]bool{}
		for _, op := range r.manifest.Capabilities.Operations {
			supported[op] = true
		}
		var cells []string
		for _, op := range operationOrder {
			if supported[op] {
				cells = append(cells, "✅")
			} else {
				cells = append(cells, "-")
			}
		}
		nextActions := append([]string{}, r.manifest.Capabilities.NextActions...)
		sort.Strings(nextActions)
		b.WriteString(fmt.Sprintf("| %s | %s | %s |\n", r.manifest.Provider, strings.Join(cells, " | "), strings.Join(nextActions, ", ")))
	}

	return b.String(), nil
}

var operationOrder = []string{"collect", "sync", "payout", "cancel", "refund", "webhook"}
