// Package catalog generates the provider catalog and capability matrix
// from every provider's metadata.yaml plus its manifest.yaml or, for a
// native provider, its capabilities.yaml: see docs/add-a-provider.md and
// .github/workflows/docs.yml. This keeps the generated docs inside the
// one piece of application code this repository permits, rather than a
// separate script living outside tools/ (spec/00-overview.md's governing
// rule).
package catalog

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/esiipayment/esiipayment-spec/tools/validator/internal/model"
)

// row is one catalog line, populated from either a manifest.yaml or a
// native provider's capabilities.yaml. Both kinds appear in the same
// table on purpose: which onboarding track a provider took is a fact an
// integrator needs (a native provider needs support built into their
// runtime, where a manifest one needs only a runtime that already
// interprets the DSL), so it is a column rather than a separate table.
type row struct {
	provider    string
	displayName string
	country     string
	currencies  []string
	operations  []string
	nextActions []string
	native      bool
	metadata    *model.Metadata
}

// Generate renders the provider catalog and capability matrix as
// Markdown, reading every providers/<name>/metadata.yaml plus its
// manifest.yaml or capabilities.yaml, except providers/_template*.
func Generate(repoRoot string) (string, error) {
	providersDir := filepath.Join(repoRoot, "providers")
	entries, err := os.ReadDir(providersDir)
	if err != nil {
		return "", fmt.Errorf("reading %s: %w", providersDir, err)
	}

	var rows []row
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), "_") {
			continue
		}
		dir := filepath.Join(providersDir, e.Name())

		r, err := loadRow(dir)
		if err != nil {
			return "", err
		}
		md, err := model.LoadMetadata(dir)
		if err != nil {
			return "", fmt.Errorf("loading %s: %w", dir, err)
		}
		r.metadata = md
		rows = append(rows, r)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].provider < rows[j].provider })

	var b strings.Builder
	b.WriteString("<!-- GENERATED by `esiipayment catalog` (tools/validator): do not hand-edit. -->\n")
	b.WriteString("<!-- Regenerate with .github/workflows/docs.yml, or `esiipayment catalog` locally. -->\n\n")
	b.WriteString("# Provider Catalog\n\n")
	b.WriteString("| Provider | Kind | Country | Tier | Verification | Currencies | Operations |\n")
	b.WriteString("|---|---|---|---|---|---|---|\n")
	for _, r := range rows {
		verification := r.metadata.Verification.Status
		if verification == "provisional" {
			verification = "⚠️ provisional"
		} else if verification == "verified" {
			verification = "✅ verified"
		}
		b.WriteString(fmt.Sprintf("| %s (%s) | %s | %s | %s | %s | %s | %s |\n",
			r.displayName, r.provider, kindLabel(r.native), r.country, r.metadata.Tier,
			verification, strings.Join(r.currencies, ", "), strings.Join(r.operations, ", ")))
	}

	b.WriteString("\n# Capability Matrix\n\n")
	b.WriteString("| Provider | " + strings.Join(operationOrder, " | ") + " | NextAction variants |\n")
	b.WriteString("|---|" + strings.Repeat("---|", len(operationOrder)) + "---|\n")
	for _, r := range rows {
		supported := map[string]bool{}
		for _, op := range r.operations {
			supported[op] = true
		}
		var cells []string
		for _, op := range operationOrder {
			if supported[op] {
				cells = append(cells, "✅")
			} else {
				cells = append(cells, "-")
			}
		}
		nextActions := append([]string{}, r.nextActions...)
		sort.Strings(nextActions)
		b.WriteString(fmt.Sprintf("| %s | %s | %s |\n", r.provider, strings.Join(cells, " | "), strings.Join(nextActions, ", ")))
	}

	return b.String(), nil
}

// loadRow reads whichever of the two provider kinds dir actually is.
// Deciding on the presence of capabilities.yaml (model.IsNativeProvider)
// rather than on the absence of manifest.yaml keeps the error message for
// a provider directory missing both files pointed at the manifest, which
// is what the overwhelming majority of contributors meant to write.
func loadRow(dir string) (row, error) {
	if model.IsNativeProvider(dir) {
		c, err := model.LoadCapabilities(dir)
		if err != nil {
			return row{}, fmt.Errorf("loading %s: %w", dir, err)
		}
		return row{
			provider:    c.Provider,
			displayName: c.DisplayName,
			country:     c.Country,
			currencies:  c.Currencies,
			operations:  c.Capabilities.Operations,
			nextActions: c.Capabilities.NextActions,
			native:      true,
		}, nil
	}

	m, err := model.LoadManifest(dir)
	if err != nil {
		return row{}, fmt.Errorf("loading %s: %w", dir, err)
	}
	return row{
		provider:    m.Provider,
		displayName: m.DisplayName,
		country:     m.Country,
		currencies:  m.Currencies,
		operations:  m.Capabilities.Operations,
		nextActions: m.Capabilities.NextActions,
	}, nil
}

// kindLabel names the onboarding track, linking the native one to the
// five signals that justify it so a reader of the catalog can see why a
// provider is not a manifest without going hunting.
func kindLabel(native bool) string {
	if native {
		return "[native](https://spec.esiipayment.et/spec/03-manifest-dsl/#native-providers)"
	}
	return "manifest"
}

var operationOrder = []string{"collect", "sync", "payout", "cancel", "refund", "webhook"}
